dist: trusty

jobs:
  include:
    - stage: Docker build Stage
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" -- password-stdin
        - docker build -t devops .
        - docker images
        - docker tag devops $DOCKER_USERNAME/devops:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/devops:$TRAVIS_BUILD_NUMBER
        - docker tag devops $DOCKER_USERNAME/devops
        - docker push $DOCKER_USERNAME/devops:lastest