language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
jobs:
  include:
    - stage: Test Stage
      before_scripts:
      - npm install
      script:
        - npm test
      after_success:
        - echo "Test Success!"
    - stage: Docker build Stage
      script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t myrepo .
        - docker images
        - docker tag myrepo $DOCKER_USERNAME/myrepo:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/myrepo:$TRAVIS_BUILD_NUMBER
        - docker tag myrepo $DOCKER_USERNAME/myrepo
        - docker push $DOCKER_USERNAME/myrepo:latest