dist: trusty

jobs:
  include:
    - stage: Docker build Stage
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t myrepo .
        - docker images
        - docker tag myrepo $DOCKER_USERNAME/myrepo:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/myrepo:$TRAVIS_BUILD_NUMBER
        - docker tag myrepo $DOCKER_USERNAME/myrepo
        - docker push $DOCKER_USERNAME/myrepo:latest